project_name: gh-extension-template

builds:
  - binary: gh-extension-template
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: binary

release:
  prerelease: auto

changelog:
  sort: asc
